### ISSUE TITLE
Fix enter new player lag

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/quick-hit#12] opened 2021-06-22 09:03 UTC
Could be the icons

**Comment by ChrisNeedham24** [comment] 2021-06-22 10:25
Confirmed it is the icons, if you remove the select, there's no lag. Looking at ways to fix it now.

**Comment by jamesgiu** [comment] 2021-06-22 10:39
RIP, maybe if we turn off that broken "filtering"?

**Comment by ChrisNeedham24** [comment] 2021-06-22 10:43
> RIP, maybe if we turn off that broken "filtering"?

Nah it's not that, I've done some research and it looks like the Semantic UI dropdown/select just doesn't cope well with large amounts of options. I've seen at least one person say that they've had success using just a regular <select> so I might take a look at that if I can't get this working.

**Comment by ChrisNeedham24** [comment] 2021-06-22 11:13
If it's okay to just have the icon name in the select and then the preview displayed for the user, I've got a solution doing that using a regular `<select>`. I'll push my changes to my branch (QH-12)

**Comment by jamesgiu** [comment] 2021-06-22 11:38
Nice, yeah that's a potential workaround too

**Comment by ChrisNeedham24** [comment] 2021-06-23 02:49
Turns out that by deploying to GitHub pages, the JS is made more efficient, so there's no lag when entering a new player name. Since most (if not all) people will be accessing the application via the deployment, we can close this.

**Closed by ChrisNeedham24** 2021-06-23 02:49 UTC
Labels: UI, bug
